#!/bin/bash

arg=$1
if [ $# -gt 1 ] ; then
    echo "This script get at most one argument"
    echo "Usage:"
    echo "$0 [-l|--logout]"
    echo ""
    echo "  -l | --logout   Logout after migration"
fi

if ! [ -d $HOME/.config/steam-buddy ] && \
    ! [ -d $HOME/.local/share/steam-buddy ] && \
    ! [ -d $HOME/.cache/steam-buddy ] ;
then
    # Nothing to migrate, we can exit
    echo "Found nothing to migrate"
    exit 0
fi

## MIGRATION MAGIC ##

# Check if there are config files from steam-buddy
if [ -d $HOME/.config/steam-buddy ] ; then
    if [ -d $HOME/.config/chimera ] ; then
        cp -Rbv $HOME/.config/steam-buddy/* $HOME/.config/chimera/.
        rm -rfv $HOME/.config/steam-buddy
        echo "Configuration directories have been merged and existing chimera files been backed up"
    else
        mv $HOME/.config/steam-buddy $HOME/.config/chimera
        echo "Configuration directory has been moved"
    fi
fi

# Migrate user data directories and files from steam-buddy
if [ -d $HOME/.local/share/steam-buddy ] ; then
    if [ -d $HOME/.local/share/chimera ] ; then
        cp -Rbv $HOME/.local/share/steam-buddy/* $HOME/.local/share/chimera/.
        rm -rfv $HOME/.local/share/steam-buddy
        echo "Data directories have been merged and existing chimera files been backed up"
    else
        mv $HOME/.local/share/steam-buddy $HOME/.local/share/chimera
        echo "Data directory has been moved"
    fi
fi

# Check if there are platform specific yaml files
platforms=('32x'
           '3do'
           'arcade'
           'atari-2600'
           'dreamcast'
           'epic-store'
           'flathub'
           'gb'
           'gba'
           'gbc'
           'gc'
           'gog'
           'sgg'
           'genesis'
           'jaguar'
           'sms'
           'neo-geo'
           'nes'
           'n64'
           'ps1'
           'ps2'
           'psp'
           'saturn'
           'sega-cd'
           'snes'
           'tg-16')
if [ -d $HOME/.local/share/steam-shortcuts ] ; then
    cd $HOME/.local/share/steam-shortcuts
    for p in ${platforms[@]} ; do
        if [ -f "steam-buddy.${p}.yaml" ] ; then
            cp -bv "steam-buddy.${p}.yaml" "chimera.${p}.yaml"
            rm -v "steam-buddy.${p}.yaml"
            echo "Renamed steam-buddy.${p}.yaml to chimera.${p}.yaml"
        fi
    done
fi

# Go to shortcuts and replace paths
if [ -d $HOME/.local/share/chimera/settings ]; then
    cd $HOME/.local/share/steam-shortcuts
    echo "Renamig relevant paths inside shortcuts files"
    find . -type f -name "*.yaml" -exec sed -i 's/steam-buddy/chimera/g' {} \; -print
fi

# Go to our directories and replace settings:
if [ -f $HOME/.local/share/chimera/settings/settings.json ]; then
    cd $HOME/.local/share/chimera/settings
    echo "Renamig relevant paths inside settings file"
    sed -i 's/steam-buddy/chimera/g' settings.json
fi

# Go to steam-grid symlinks and relink them
cd $HOME/.local/share/Steam/userdata
for u in * ; do
    if [ -d $u ] ; then
        if ! [ "$(basename $u)" == "anonymous" ] &&
            ! [ "$(basename $u)" == "ac" ] ; then
            echo "Relinking steam grid for user $(basename $u)"
            if [ -d $u/config/grid ] ; then
                cd $u/config/grid
                for l in * ; do
                    if [[ -L $l ]] ; then
                        old_link=$(readlink ${l})
                        new_link=${old_link/steam-buddy/chimera}
                        ln -sfv $new_link $l
                    fi
                done
            fi
        fi
    fi
done


# Logout the session since we need to restart everything in ChimeraOS
case $arg in
    -l | --logout)
        echo "Migration finished. You'll be logged out"
        sleep 2
        logout
        ;;
    *)
        echo "Migration Finished. You may need to restart chimera and Steam"
        ;;
esac
