#!/usr/bin/env python

import os
import yaml
import shutil
from bottle import route, request, static_file, run, template, redirect

DATA_DIR='/var/lib/steam-buddy'
SHORTCUT_DIR=DATA_DIR + '/shortcuts'
BANNER_DIR=DATA_DIR + '/banners'
CONTENT_DIR=DATA_DIR + '/content'

PLATFORMS = {
	"gba"     : "Game Boy Advance",
	"genesis" : "Genesis",
	"sms"     : "Master System",
	"nes"     : "Nintendo",
	"snes"    : "Super Nintendo",
}


def load_shortcuts(platform):
	shortcuts = []
	if not os.path.exists(SHORTCUT_DIR):
		os.makedirs(SHORTCUT_DIR)
	shortcuts_file = "{shortcuts_dir}/{platform}.yaml".format(shortcuts_dir=SHORTCUT_DIR, platform=platform)
	if os.path.isfile(shortcuts_file):
		shortcuts = yaml.load(open(shortcuts_file), Loader=yaml.FullLoader)

	if not shortcuts:
		shortcuts = []

	return shortcuts

def get_path(base_dir, platform, name):
	return "{base_dir}/{platform}/{name}".format(base_dir=base_dir, platform=platform, name=name)

def upsert_file(data, base_dir):
	if not data:
		return

	if not os.path.exists(base_dir):
		os.makedirs(base_dir)

	file_path = "{base_dir}/{filename}".format(base_dir=base_dir, filename=data.filename)
	if os.path.exists(file_path):
		os.remove(file_path)

	data.save(file_path)

def delete_folder(target_dir):
	if os.path.exists(target_dir):
		shutil.rmtree(target_dir)


@route('/')
def root():
	return template('platforms.tpl', platforms=PLATFORMS)

@route('/platforms/<platform>')
def platform(platform):
	shortcuts = sorted(load_shortcuts(platform), key=lambda s: s['name'])
	data = []
	for shortcut in shortcuts:
		filename = None
		banner = None
		hidden = 'hidden' if 'hidden' in shortcut and shortcut['hidden'] else ''
		if 'banner' in shortcut:
			filename = os.path.basename(shortcut['banner'])
			banner = '/banners/{platform}/{name}/{filename}'.format(platform=platform, name=shortcut['name'], filename=filename)
		data.append({ 'hidden' : hidden, 'filename' : filename, 'banner' : banner, 'name' : shortcut['name'] })

	return template('platform.tpl', shortcuts=data, platform=platform, platformName=PLATFORMS[platform])

@route('/banners/<platform>/<name>/<filename>')
def banners(platform, name, filename):
	base = "{banner_dir}/{platform}/{name}".format(banner_dir=BANNER_DIR, platform=platform, name=name)
	return static_file(filename, root='{base}'.format(base=base))

@route('/platforms/<platform>/new')
def new(platform):
	return template('new.tpl', isNew=True, isEditing=False, platform=platform, platformName=PLATFORMS[platform], name='', hidden='')

@route('/platforms/<platform>/edit/<name>')
def edit(platform, name):
	shortcuts_file = "{shortcuts_dir}/{platform}.yaml".format(shortcuts_dir=SHORTCUT_DIR, platform=platform)
	shortcuts = load_shortcuts(platform)

	matches = [e for e in shortcuts if e['name'] == name and e['cmd'] == platform]
	shortcut = matches[0]

	return template('new.tpl', isEditing=True, platform=platform, platformName=PLATFORMS[platform], name=name, hidden=shortcut['hidden'])

@route('/images/<filename>')
def images(filename):
	return static_file('images/' + filename, root='.')

@route('/shortcuts/new', method='POST')
def shortcut_create():
	name = request.forms.get('name')
	platform = request.forms.get('platform')
	hidden = request.forms.get('hidden')
	banner = request.files.get('banner')
	content = request.files.get('content')

	if name == None or name.strip() == '':
		redirect('/platforms/{platform}/new'.format(platform=platform))
		return

	name = name.strip()

	shortcuts_file = "{shortcuts_dir}/{platform}.yaml".format(shortcuts_dir=SHORTCUT_DIR, platform=platform)
	shortcuts = load_shortcuts(platform)

	matches = [e for e in shortcuts if e['name'] == name and e['cmd'] == platform]
	if len(matches) > 0:
		return 'Shortcut already exists'

	banner_dir = get_path(BANNER_DIR, platform, name)
	upsert_file(banner, banner_dir)

	content_dir = get_path(CONTENT_DIR, platform, name)
	upsert_file(content, content_dir)

	shortcut = {}
	shortcut['name'] = name
	shortcut['cmd'] = platform
	shortcut['hidden'] = hidden == 'on'
	shortcut['tags'] = [ PLATFORMS[platform] ]
	if banner:
		shortcut['banner'] = '{banner_dir}/{filename}'.format(banner_dir=banner_dir, filename=banner.filename)
	if content:
		shortcut['dir'] = '"' + content_dir + '"'
		shortcut['params'] = '"' + content.filename + '"'

	shortcuts.append(shortcut)
	yaml.dump(shortcuts, open(shortcuts_file, 'w'), default_flow_style=False)

	redirect('/platforms/{platform}'.format(platform=platform))

@route('/shortcuts/edit', method='POST')
def shortcut_update():
	name = request.forms.get('original_name') # do not allow editing name
	platform = request.forms.get('platform')
	hidden = request.forms.get('hidden')
	banner = request.files.get('banner')
	content = request.files.get('content')

	shortcuts_file = "{shortcuts_dir}/{platform}.yaml".format(shortcuts_dir=SHORTCUT_DIR, platform=platform)
	shortcuts = load_shortcuts(platform)

	banner_dir = get_path(BANNER_DIR, platform, name)
	upsert_file(banner, banner_dir)

	content_dir = get_path(CONTENT_DIR, platform, name)
	upsert_file(content, content_dir)

	matches = [e for e in shortcuts if e['name'] == name and e['cmd'] == platform]
	shortcut = matches[0]
	shortcut['name'] = name
	shortcut['cmd'] = platform
	shortcut['hidden'] = hidden == 'on'
	if banner:
		shortcut['banner'] = '{banner_dir}/{filename}'.format(banner_dir=banner_dir, filename=banner.filename)
	if content:
		shortcut['dir'] = '"' + content_dir + '"'
		shortcut['params'] = '"' + content.filename + '"'

	yaml.dump(shortcuts, open(shortcuts_file, 'w'), default_flow_style=False)

	redirect('/platforms/{platform}'.format(platform=platform))

@route('/shortcuts/delete', method='POST')
def shortcut_delete():
	name = request.forms.get('name')
	platform = request.forms.get('platform')

	shortcuts_file = "{shortcuts_dir}/{platform}.yaml".format(shortcuts_dir=SHORTCUT_DIR, platform=platform)
	shortcuts = load_shortcuts(platform)

	matches = [e for e in shortcuts if e['name'] == name and e['cmd'] == platform]
	shortcut = matches[0]

	delete_folder(get_path(CONTENT_DIR, platform, name))
	delete_folder(get_path(BANNER_DIR, platform, name))

	shortcuts.remove(shortcut)
	yaml.dump(shortcuts, open(shortcuts_file, 'w'), default_flow_style=False)

	redirect('/platforms/{platform}'.format(platform=platform))

if __name__ == '__main__':
	run(host='0.0.0.0', port=80)
