#!/usr/bin/env python3
import os
from steam_buddy import server
from steam_buddy.config import RESOURCE_DIR

if __name__ == '__main__':
	os.chdir(RESOURCE_DIR)
	server.run(host='localhost', port=8844)
