#! /bin/bash

/usr/share/chimera/bin/migrations/01-chimera-dir --logout
/usr/share/chimera/bin/migrations/02-multi-image-types
chimera --update --tweaks
chimera --images & # do not wait for image downloads

# make sure the patch service picks up the latest downloaded data
systemctl --user restart steam-patch
