#!/bin/bash

set -x
set -e

COMMIT=19669ca372ddd3993e10dc287132edb172188e3e

PROTON_VERSION=${1}
LD_LIBRARY_PATH=/usr/lib

CACHE_DIR=${XDG_CACHE_HOME:-$HOME/.cache}/steam-tweaks
mkdir -p ${CACHE_DIR}
cd ${CACHE_DIR}

if [ ! -d "mf-install-${COMMIT}" ]; then
	curl -L https://github.com/z0z0z/mf-install/archive/${COMMIT}.tar.gz -o mf-install.tar.gz
	tar xf mf-install.tar.gz
	rm mf-install.tar.gz
fi

cd mf-install-${COMMIT}
PROTON="${STEAM_COMPAT_CLIENT_INSTALL_PATH}/steamapps/common/Proton ${PROTON_VERSION}" WINEPREFIX="${STEAM_COMPAT_DATA_PATH}/pfx" ./mf-install.sh -proton
