#!/bin/bash

echo "migration start: $0"

DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
CHIMERA=$DATA_HOME/chimera

if [ -d $CHIMERA/content/gc ]; then
	echo "renaming content/gc"
	mv $CHIMERA/content/gc $CHIMERA/content/ngc
fi

if [ -d $CHIMERA/saves/gc ]; then
	echo "renaming saves/gc"
	mv $CHIMERA/saves/gc $CHIMERA/saves/ngc
fi

if [ -d $CHIMERA/images/background/gc ]; then
	echo "renaming images/background/gc"
	mv $CHIMERA/images/background/gc $CHIMERA/images/background/ngc
fi

if [ -d $CHIMERA/images/banner/gc ]; then
	echo "renaming images/banner/gc"
	mv $CHIMERA/images/banner/gc $CHIMERA/images/banner/ngc
fi

if [ -d $CHIMERA/images/icon/gc ]; then
	echo "renaming images/icon/gc"
	mv $CHIMERA/images/icon/gc $CHIMERA/images/icon/ngc
fi

if [ -d $CHIMERA/images/logo/gc ]; then
	echo "renaming images/logo/gc"
	mv $CHIMERA/images/logo/gc $CHIMERA/images/logo/ngc
fi

if [ -d $CHIMERA/images/poster/gc ]; then
	echo "renaming images/poster/gc"
	mv $CHIMERA/images/poster/gc $CHIMERA/images/poster/ngc
fi

if [ -f $CHIMERA/shortcuts/chimera.gc.yaml ]; then
	echo "renaming shortcuts/chimera.gc.yaml"
	mv $CHIMERA/shortcuts/chimera.gc.yaml $CHIMERA/shortcuts/chimera.ngc.yaml
fi

if [ -d $CHIMERA/shortcuts ]; then
	pushd $CHIMERA/shortcuts > /dev/null

	if grep "cmd: gc$" chimera.ngc.yaml &> /dev/null; then
	    echo "renaming shortcut commands"
	    sed -i 's|cmd: gc$|cmd: ngc|' chimera.ngc.yaml;
	fi

	if grep "/gc\"" chimera.ngc.yaml &> /dev/null; then
	    echo "renaming shortcut execution directories"
	    sed -i 's|/gc"|/ngc"|' chimera.ngc.yaml;
	fi

	if grep "/gc/" chimera.ngc.yaml &> /dev/null; then
	    echo "renaming shortcut image paths"
	    sed -i 's|/gc/|/ngc/|' chimera.ngc.yaml;
	fi

	popd > /dev/null
fi

echo "migration finish: $0"
