#!/usr/bin/env python
import sys
import pyglet


class Color:
    TEXT = (252, 252, 252, 255)
    BACKGROUND = (15, 47, 78, 255)


# Load the password from the command line arguments
if len(sys.argv) > 1:
    password = sys.argv[1]
else:
    print("No password to show specified")
    exit(1)

# Initialize window
window = pyglet.window.Window(fullscreen=True)

# Setup joystick events
joysticks = pyglet.input.get_joysticks()

def on_joybutton_press(joystick, button_name):
    pyglet.app.exit()

for joystick in joysticks:
    joystick.open(window)
    joystick.on_joybutton_press = on_joybutton_press

# Solid Background
background = pyglet.sprite.Sprite(
    pyglet.image.SolidColorImagePattern(color=Color.BACKGROUND).create_image(
        window.width, window.height)
)

# Display text instructions
font_size = (window.width//20)

password_label = pyglet.text.Label(password,
                                   font_name='dejavusans',
                                   font_size=font_size,
                                   x=window.width//2,
                                   y=window.height//2,
                                   anchor_x='center',
                                   anchor_y='center')
password_label.bold=True
password_label.color=Color.TEXT

quit_label = pyglet.text.Label("Press any button or ESC to exit this screen",
                               font_name='dejavusans',
                               font_size=font_size//2,
                               x=window.width//2,
                               y=font_size,
                               anchor_x='center',
                               anchor_y='center')
quit_label.color=Color.TEXT

instructions_label = pyglet.text.Label("Your password for the web interface is:",
                               font_name='dejavusans',
                               font_size=font_size//2,
                               x=window.width//2,
                               y=window.height - font_size,
                               anchor_x='center',
                               anchor_y='center')
instructions_label.color=Color.TEXT

@window.event
def on_draw():
    window.clear()
    background.draw()
    instructions_label.draw()
    password_label.draw()
    quit_label.draw()

@window.event
def on_key_press(symbol, modifiers):
    if symbol == pyglet.window.key.ESCAPE:
        pyglet.app.exit()

@window.event
def on_mouse_press(x, y, button, modifiers):
    pyglet.app.exit()

def main():
    pyglet.app.run()

if __name__ == "__main__":
    main()
