#!/usr/bin/env python
import argparse
import pyglet
import os.path
from chimera_app.config import RESOURCE_DIR
from chimera_app.config import SETTINGS_DIR

PIPE_FILE=str()

window = pyglet.window.Window(fullscreen=True)
batch = pyglet.graphics.Batch()

text_size = int(window.height//32)
label = pyglet.text.Label("",
                          font_name='dejavusans',
                          font_size=text_size,
                          x=window.width//2,
                          y=text_size * 5,
                          anchor_x='center', anchor_y='center',
                          batch=batch
                         )

custom_image_path = os.path.join(SETTINGS_DIR, 'splash.png')
if os.path.exists(custom_image_path):
    background_image_path = custom_image_path
else:
    background_image_path = os.path.join(RESOURCE_DIR, 'images', 'splash', 'chimeraos_logo.png')

background_image = pyglet.image.load(background_image_path)
background = pyglet.sprite.Sprite(img=background_image, batch=batch)

# Center and scale to screen
background.scale=0.4 * window.height / background.height
background.x = window.width//2 - background.width // 2
background.y = window.height//2 - background.height // 2


pyglet.gl.glClearColor(0, 0, 0, 1.0)

def update_label():
    with open(PIPE_FILE, 'r', encoding='utf-8') as message_file:
        label.text = f"{message_file.readlines()[-1]}".strip()

@window.event
def on_draw():
    if PIPE_FILE:
        update_label()
    window.clear()
    batch.draw()

@window.event
def on_close():
    pass

def arg_parse():
    parser = argparse.ArgumentParser(description="Simple ChimeraOS splash screen")
    parser.add_argument("-p", "--pipe-file",
                        action='store',
                        type=str,
                        help="Pipe file to check percentage"
                       )

    return parser.parse_args()

def main():
    global PIPE_FILE

    args = arg_parse()

    if args.pipe_file:
        PIPE_FILE = args.pipe_file

    pyglet.app.run()

if __name__ == "__main__":
    main()
