#! /bin/bash

DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

if [ -z ${RETRO_CORE} ]; then
	RETRO_CORE=${2}
fi

SAVE_DIR=${DATA_HOME}/chimera/saves/${1}
RETRO_CONFIG=/tmp/chimera-retroarch.cfg

CORE_CONFIG=/usr/share/chimera/config/${1}.cfg
LOCAL_CONFIG=${CONFIG_HOME}/chimera/${1}.cfg
if [ -f ${LOCAL_CONFIG} ]; then
	CORE_CONFIG=${LOCAL_CONFIG}
fi

shift 2

ROM_PATH=$(realpath "$@")

mkdir -p ${SAVE_DIR}

COMMON_CONFIG=/usr/share/chimera/config/retroarch-common.cfg
LOCAL_COMMON_CONFIG=${CONFIG_HOME}/chimera/retroarch-common.cfg
if [ -f ${LOCAL_COMMON_CONFIG} ]; then
	COMMON_CONFIG=${LOCAL_COMMON_CONFIG}
fi

cp ${COMMON_CONFIG} ${RETRO_CONFIG}
echo "
savefile_directory = ${SAVE_DIR}
savestate_directory = ${SAVE_DIR}
" >> ${RETRO_CONFIG}


mkdir -p ${CONFIG_HOME}/retroarch
AUTOCONFIG=${CONFIG_HOME}/retroarch/autoconfig
if [ ! -e ${AUTOCONFIG} ] || [ -L ${AUTOCONFIG} ]; then
	rm -f ${AUTOCONFIG}
	mkdir -p ${AUTOCONFIG}
fi

if [ ! -e ${AUTOCONFIG}/steam-virtual-gamepad.cfg ]; then
	ln -s /usr/share/chimera/config/steam-virtual-gamepad.cfg ${AUTOCONFIG}/
fi

# use the RetroArch config as is, allowing users to manually configure RetroArch if they want to
if [ "${CHIMERA_DISABLE_RETROARCH_CONFIG_OVERRIDES}" == "1" ]; then
	retroarch \
	--libretro /usr/lib/libretro/${RETRO_CORE}_libretro.so \
	"$ROM_PATH"
	exit $?
fi

if [ -e ${CORE_CONFIG} ]; then
	cp ${CORE_CONFIG} ${CONFIG_HOME}/retroarch/retroarch-core-options.cfg
fi

if [ "${RETRO_CORE}" == "dolphin" ]; then
	mkdir -p ${CONFIG_HOME}/retroarch/config/remaps/dolphin-emu
	cp -f ${CORE_CONFIG} ${CONFIG_HOME}/retroarch/config/remaps/dolphin-emu/dolphin-emu.rmp
fi

# Ignore all controller devices except for Steam Input
export SDL_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT="0x28de/0x11ff"

retroarch \
--appendconfig "${RETRO_CONFIG}|${CORE_CONFIG}" \
--libretro /usr/lib/libretro/${RETRO_CORE}_libretro.so \
"$ROM_PATH"
