#! /bin/bash

if [ "${1}" == "get-tdp" ]; then
	ryzenadj --info | grep stapm-limit | cut -d '|' -f 3 | tr -d ' ' | cut -d '.' -f 1
fi

if [ "${1}" == "set-tdp" ]; then
	target=${2}
	boost=2
	if [ -n "$3" ]; then
		boost=${3}
	fi

	let "target_tdp = $(($target * 1000))"
	let "boost_slow = $((($target + $boost / 2) * 1000))"
	let "boost_fast = $((($target + $boost) * 1000))"

	ryzenadj --stapm-limit=${target_tdp} --fast-limit=${boost_fast} --slow-limit=${boost_slow} &> /dev/null
fi
