#!/bin/bash

# Linux
if [ -f start.sh ]; then
	echo ./start.sh
	exit
fi

# Windows
rm -rf tmp
appdir=$(dirname `find . -name "goggame*.info"`)

if [ "$appdir" != "." ]; then
	mv $appdir/* .
	rm -rf $appdir
fi

exe=$(yq ".[] | select(.id == ${1}) | select(.platform == \"gog\") | .exe" ~/.local/share/chimera/data/gamedb.yaml)

if [ -n "$exe" ] && [ "$exe" != "null" ]; then
	echo $exe | sed 's/"//g'
	exit
fi

cat goggame*.info | jq '.playTasks[0].path' | sed 's/"//g'
