#! /bin/bash

if [ ! -e ~/.config/retroarch/system/pcsx2 ]; then
	mkdir -p ~/.config/retroarch/system/pcsx2
	ln -s ~/.local/share/chimera/content/ps2 ~/.config/retroarch/system/pcsx2/bios
fi

/usr/share/chimera/bin/launcher ps2 pcsx2 "$@"
