#! /bin/bash
romname="${@%.zip}"
#cd .snesmsu1
mkdir tmp
fuse-zip -r "$@" tmp
/usr/share/chimera/bin/launcher snesmsu1 snes9x "$HOME/.local/share/chimera/content/snesmsu1/.snesmsu1/tmp/$romname"
umount tmp
rmdir tmp
